/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1cjXgVxpaPV
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Amplify } from 'aws-amplify'
import { list } from 'aws-amplify/storage'
import { FormEvent, useEffect, useState } from 'react'
import { generateClient } from 'aws-amplify/data'
import type { Schema } from '@/amplify/data/resource'

const defaultMsg = {
	id: '1',
	author: 'Bot',
	text: 'Hey! I know a lot of stuff about a file called "setlist" feel free to ask my any questions about it! You can even ask followup questions as well!',
}
const fileName = 'setlist.csv'

export function ChatPage({ bucketName, signOut }: { bucketName: string }) {
	const client = generateClient<Schema>()
	const [msgText, setMsgText] = useState('')
	const [msgs, setMsgs] = useState<Array<string>>([defaultMsg])
	const [bucketInfo, setBucketInfo] = useState({
		bucketName,
		fileName: '',
	})

	useEffect(() => {
		list().then((data) => {
			const setlist = data.items.find((item) => item.key === fileName)
			setBucketInfo({ bucketName, fileName })
		})
	}, [bucketName])

	const handleFormSubmit = async (e: FormEvent) => {
		e.preventDefault()

		const { data } = await client.mutations.generateTextFromPrompt(
			{
				text: msgText,
				bucketName: bucketInfo.bucketName,
				fileName: bucketInfo.fileName,
			},
			{ authMode: 'iam' }
		)

		console.log('the data', data)
	}
	return (
		<div className="flex flex-col h-screen">
			<header className="bg-gray-900 text-white py-4 px-6 flex items-center">
				<div className="flex-1">
					<h2 className="text-lg font-medium">Focus Otter</h2>
				</div>
				<div onClick={signOut}>Signout</div>
			</header>
			<div className="flex-1 overflow-y-auto p-6 space-y-4">
				<div className="flex">
					<div className="bg-gray-200 text-gray-800 px-4 py-2 rounded-lg max-w-[40%]">
						<p>
							Hey! I know a lot of stuff about a file called "setlist" feel free
							to ask my any questions about it! You can even ask followup
							questions as well!
						</p>
					</div>
				</div>
				<div className="flex justify-end">
					<div className="bg-blue-500 text-white px-4 py-2 rounded-lg max-w-[70%]">
						<p>Hey there! How's it going?</p>
					</div>
				</div>
			</div>
			<form
				onSubmit={handleFormSubmit}
				className="bg-gray-100 py-4 px-6 flex items-center"
			>
				<input
					className="flex-1 border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
					placeholder="Type your message..."
					type="text"
					value={msgText}
					onChange={(e) => setMsgText(e.target.value)}
				/>
				<button
					type="submit"
					className="ml-4 bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600"
				>
					Send
				</button>
			</form>
		</div>
	)
}
